# services:
#   redis:
#     image: "redis:latest"
#     container_name: redis
#     restart: always
#     ports:
#       - "6379:6379"
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 5s
#       timeout: 5s
#       retries: 5
#     networks:
#       - backend-network

#   main-backend:
#     build: ./main-backend
#     container_name: main-backend
#     restart: always
#     ports:
#       - "3000:3000"
#     networks:
#       - backend-network
#     depends_on:
#       redis:
#         condition: service_healthy
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#       - NODE_ENV=development

# networks:
#   backend-network:
#     driver: bridge
